function Result = SpectrumVsPowerLaw(X, fs, options)
    % ===============================================================================================================
    % SPECTRUM vs. POWER-LAW (1/f) NULL: is there MORE energy in a frequency band than a smooth 1/f^beta spectrum predicts?
    % ===============================================================================================================
    % Signal-agnostic core. It knows nothing about speech or EEG: hand it any set of equal-rate time series (speech-
    % envelope epochs, EEG epochs, ...) and it will
    %
    %   1. estimate the power spectral density (PSD) with Welch's method, using this repo's own
    %      WelchCrossSpectralDensity.m / CrossSpectralDensity.m (Hann window, per-segment mean removal, PSD units of
    %      power/Hz, one-sided) -- the same spectral estimator the coherence pipeline uses;
    %   2. fit a power law  PSD(f) = 10^a * f^(-beta)  in log-log space to the FLANKS of the band of interest only (the
    %      band, plus a guard margin, is excluded from the fit), so the "expected under 1/f" curve is interpolated
    %      ACROSS the band rather than being pulled up by whatever is in it;
    %   3. report the excess of the observed spectrum over that fit (per frequency, in dB, and summed over the band);
    %   4. test the band excess against a Monte-Carlo null: Gaussian power-law noise with the fitted a and beta, run
    %      through the IDENTICAL pipeline (same epoch lengths, same Welch window, same fit, same exclusion band), so
    %      the p-value already accounts for Welch estimation noise and for uncertainty in the fitted line;
    %   5. give a family-wise-error (max-statistic) threshold across all frequencies, and a bootstrap-over-epochs
    %      confidence interval for the band excess (needs >= 4 epochs).
    %
    % Why a flank-only fit: fitting a straight line through ALL frequencies lets a genuine bump raise the "expected"
    % line and makes the bump look smaller than it is (and, with a free slope, can even tilt the line). Excluding the
    % band from the fit makes the band a genuine out-of-sample test of the flank-derived 1/f prediction.
    %
    % Why weights of 1/f in the fit: FFT bins are evenly spaced in Hz, so on a log-frequency axis there are ~10x more
    % bins per octave at 20 Hz than at 2 Hz. An unweighted fit would be dominated by the high frequencies. Weighting
    % each bin by 1/f gives every octave equal say.
    %
    % Why the estimator works on the LOG spectrum but the band statistic works on LINEAR power: log(PSD estimate) is
    % biased low (Jensen; E[ln chi2_nu/nu] = psi(nu/2) - ln(nu/2)). The fit adds that (small, approximate) correction
    % back so the fitted line represents the MEAN PSD, and the band statistic is a ratio of band-summed linear power
    % (observed / expected). Because the null distribution is generated by the very same code, any residual bias
    % cancels in the p-value anyway.
    %
    % INPUTS
    %   X   : equal-rate real time series, as ONE of
    %           - a vector (one long recording),
    %           - a [Num_samples x Num_pieces] matrix (columns = independent epochs / trials; they need not be
    %             contiguous in time -- each is Welch-analysed separately and the PSDs are averaged),
    %           - a cell array of vectors (epochs of different lengths; averaged with weights proportional to the
    %             number of Welch segments each contributes).
    %       Preprocessing is YOUR responsibility. In particular do NOT hand this function data that were band-pass
    %       filtered inside the frequency range you want to fit (e.g. the 2-35 Hz filtered signals that the coherence
    %       pipeline uses): the filter roll-off is baked into the spectrum and will masquerade as (or hide) structure.
    %       See the note on band_pass_filt.m in the accompanying script header.
    %   fs  : sampling rate of X, in Hz.
    %
    % OPTIONS (name-value)
    %   WindowDurationSec (5)   Welch window length. Frequency resolution = 1/WindowDurationSec. Must be at least
    %                           3 cycles of FitRangeHz(1) (checked with RecommendWelchWindowLength.m) and no longer
    %                           than the shortest epoch.
    %   OverlapFraction (0.5)   Welch overlap, in [0, 0.5] (same cap as WelchCrossSpectralDensity.m).
    %   FitRangeHz ([1 30])     Frequency range over which the power law is fitted (band and guard excluded).
    %   BandHz ([4 8])          The band whose energy is tested against the power-law prediction.
    %   GuardHz (1)             Margin excluded from the fit on each side of BandHz. (Real bumps have skirts.)
    %   ExcludeHz ([])          Explicit exclusion interval [lo hi]; overrides BandHz +/- GuardHz. Must contain BandHz.
    %   Exponent (NaN)          NaN = fit beta freely. Otherwise beta is FIXED to this value (1 = "pink"/1/f noise
    %                           exactly; only the offset a is then fitted).
    %   NumSurrogates (1000)    Monte-Carlo null size. 0 skips the null (no p-value / FWE threshold).
    %   NumBootstrap (1000)     Bootstrap-over-epochs size for the band-excess CI. 0 (or < 4 epochs) skips it.
    %   Alpha (0.05)            Two-sided level for the null envelope / CI; the FWE threshold is one-sided at Alpha.
    %   RandomSeed (NaN)        If not NaN, rng is seeded (and the previous generator state is restored afterward).
    %   Verbose (true)          Print a summary.
    %
    % OUTPUT  Result (struct)
    %   .Freqs, .PSD                 one-sided frequency axis (Hz) and mean Welch PSD (units of X^2/Hz)
    %   .PSD_pieces, .NumSegments    per-epoch PSDs [Num_freqs x Num_pieces] and Welch segments per epoch
    %   .FitMask/.ExcludeMask/.BandMask   logical, per frequency bin
    %   .Offset_log10, .Exponent     fitted a and beta (beta is the value you passed if it was fixed)
    %   .PSD_fit                     fitted power law at every bin (NaN at 0 Hz)
    %   .Residual_dB                 10*log10(PSD ./ PSD_fit), per bin
    %   .BandExcess_dB               10*log10(band-summed PSD / band-summed PSD_fit)   <- the headline number
    %   .PSD_pink, .BandExcess_dB_pink   same, against a beta = 1 line (offset fitted on the same flank bins)
    %   .PeakFreqHz, .PeakResidual_dB    frequency (within FitRangeHz) with the largest residual, and its size
    %   .FitR2, .FitRMSE_dB, .ExpectedFitRMSE_dB   quality of the flank fit; if FitRMSE_dB is much larger than
    %                                the expected value the flanks are NOT well described by one power law
    %                                (see the KNEE caveat below) and the band excess should be read with care.
    %   .EffectiveDoF                approximate chi-square dof (nu) of the averaged PSD estimate
    %   .Null   (only if NumSurrogates > 0): .BandExcess_dB [1 x NumSurrogates], .PValue (one-sided, upper tail,
    %           (1+#{null >= obs})/(N+1)), .Residual_dB_lo/.Residual_dB_hi (pointwise 1-Alpha null envelope of the
    %           residual), .MaxThreshold_dB (family-wise threshold on Residual_dB over FitRangeHz), .FreqSignificant
    %           (logical per bin: residual exceeds the max-statistic threshold), .NumSignificantFlankBins (how many of
    %           those bins lie INSIDE the fitted flanks -- should be ~0 for a real peak that fits inside the excluded
    %           interval; >= 3 triggers a warning: a wider-than-expected bump, or a knee), .Exponent [1 x NumSurrogates]
    %   .Bootstrap (only if run): .BandExcess_dB (vector), .CI_dB [lo hi]
    %   .Options                     the resolved options (for provenance)
    %
    % CAVEATS worth keeping in mind when interpreting a "significant excess over 1/f"
    %   * KNEE vs PEAK. The test asks "does the spectrum lie above a straight line in log-log coordinates, between
    %     its flanks?" A localized PEAK does. But so does any smooth low-pass / "knee" spectrum (flat at low
    %     frequencies, steeper above a corner frequency): it is concave in log-log, so it sits above the chord
    %     joining its flanks. Any process with a finite temporal-correlation time (e.g. a smoothed envelope) has
    %     such a knee. So look at the residual curve (PlotSpectrumVsPowerLaw.m): a peak rises and FALLS inside the
    %     band; a knee's residual is a broad hump that is not tied to the band edges. Also check .FitRMSE_dB.
    %   * The Monte-Carlo null is Gaussian and stationary. Speech envelopes are neither, exactly; with many Welch
    %     segments averaged, that mainly matters through the width of the null. Treat the bootstrap CI over epochs
    %     as the more realistic statement of uncertainty when you have >= 4 epochs.
    %   * The excess is defined relative to the fit, and the fit depends on FitRangeHz / GuardHz / Exponent. Report a
    %     few alternatives (see script_SpeechEnvelopeSpectrum_vs_1overf.m for a sensitivity table).
    % ===============================================================================================================
    arguments
        X
        fs (1,1) double {mustBePositive}
        options.WindowDurationSec (1,1) double {mustBePositive} = 5
        options.OverlapFraction (1,1) double {mustBeGreaterThanOrEqual(options.OverlapFraction, 0), mustBeLessThanOrEqual(options.OverlapFraction, 0.5)} = 0.5
        options.FitRangeHz (1,2) double {mustBePositive} = [1 30]
        options.BandHz (1,2) double {mustBePositive} = [4 8]
        options.GuardHz (1,1) double {mustBeNonnegative} = 1
        options.ExcludeHz double = []
        options.Exponent (1,1) double = NaN
        options.NumSurrogates (1,1) double {mustBeNonnegative, mustBeInteger} = 1000
        options.NumBootstrap (1,1) double {mustBeNonnegative, mustBeInteger} = 1000
        options.Alpha (1,1) double {mustBePositive} = 0.05
        options.RandomSeed (1,1) double = NaN
        options.Verbose (1,1) logical = true
    end

    % ---------------------------------------------------------------------------------------------------------------
    % 0. Input handling: turn X into a cell array of column vectors ("pieces").
    % ---------------------------------------------------------------------------------------------------------------
    if iscell(X)
        pieces = X(:)';
        for j = 1:numel(pieces), pieces{j} = pieces{j}(:); end
    elseif isnumeric(X)
        if isvector(X)
            pieces = {X(:)};
        else
            if size(X, 1) < size(X, 2)
                warning('SpectrumVsPowerLaw:Orientation', ...
                    ['X is %d x %d (more columns than rows). Columns are interpreted as independent epochs and rows as ' ...
                     'time samples; transpose X if that is not what you intended.'], size(X, 1), size(X, 2));
            end
            pieces = cell(1, size(X, 2));
            for j = 1:size(X, 2), pieces{j} = X(:, j); end
        end
    else
        error('SpectrumVsPowerLaw:BadInput', 'X must be a numeric vector/matrix or a cell array of vectors.');
    end
    Num_pieces = numel(pieces);
    piece_len = zeros(1, Num_pieces);
    for j = 1:Num_pieces
        if ~isreal(pieces{j}) || any(~isfinite(pieces{j}))
            error('SpectrumVsPowerLaw:BadInput', 'Piece %d contains NaN/Inf or complex values.', j);
        end
        piece_len(j) = numel(pieces{j});
    end

    % ---------------------------------------------------------------------------------------------------------------
    % 1. Analysis parameters: Welch window (validated with the repo's RecommendWelchWindowLength), frequency axis, masks.
    % ---------------------------------------------------------------------------------------------------------------
    overlap = options.OverlapFraction;
    shortest_dur = min(piece_len) / fs;
    WinInfo = RecommendWelchWindowLength(shortest_dur, fs, options.FitRangeHz(1), ...
        'MinCyclesPerWindow', 3, 'OverlapFraction', overlap, 'WindowDurationSec', options.WindowDurationSec);
    win_samples = WinInfo.WindowSamples;

    if mod(win_samples, 2) == 0, n_freqs = win_samples/2 + 1; else n_freqs = (win_samples + 1)/2; end   % same as CrossSpectralDensity.m
    Freqs = (0:n_freqs-1)' * (fs / win_samples);

    if isempty(options.ExcludeHz)
        excl = [options.BandHz(1) - options.GuardHz, options.BandHz(2) + options.GuardHz];
    else
        excl = options.ExcludeHz(:)';
        if numel(excl) ~= 2, error('SpectrumVsPowerLaw:BadOption', 'ExcludeHz must be [lo hi].'); end
    end
    if excl(1) > options.BandHz(1) || excl(2) < options.BandHz(2)
        error('SpectrumVsPowerLaw:ExcludeMustContainBand', ...
            'The excluded interval [%.2f %.2f] Hz must contain BandHz [%.2f %.2f] Hz, otherwise the band would influence its own null.', ...
            excl(1), excl(2), options.BandHz(1), options.BandHz(2));
    end
    if options.FitRangeHz(1) >= excl(1) || options.FitRangeHz(2) <= excl(2)
        error('SpectrumVsPowerLaw:NoFlanks', ...
            'FitRangeHz [%.2f %.2f] must extend beyond the excluded interval [%.2f %.2f] on BOTH sides (otherwise there is no flank to fit).', ...
            options.FitRangeHz(1), options.FitRangeHz(2), excl(1), excl(2));
    end
    if options.FitRangeHz(2) > fs/2
        error('SpectrumVsPowerLaw:AboveNyquist', 'FitRangeHz(2) = %.2f Hz exceeds Nyquist (%.2f Hz).', options.FitRangeHz(2), fs/2);
    end
    RangeMask   = Freqs >= options.FitRangeHz(1) & Freqs <= options.FitRangeHz(2);
    ExcludeMask = Freqs >= excl(1) & Freqs <= excl(2);
    FitMask     = RangeMask & ~ExcludeMask;
    BandMask    = Freqs >= options.BandHz(1) & Freqs <= options.BandHz(2);
    n_low  = sum(FitMask & Freqs < excl(1));
    n_high = sum(FitMask & Freqs > excl(2));
    if n_low < 5 || n_high < 5 || sum(BandMask) < 2
        error('SpectrumVsPowerLaw:TooFewBins', ...
            ['Only %d (low flank) / %d (high flank) fit bins and %d band bins at %.3f Hz resolution -- need >= 5 per flank and >= 2 in the band. ' ...
             'Use a longer WindowDurationSec or wider flanks.'], n_low, n_high, sum(BandMask), fs/win_samples);
    end

    if ~isnan(options.RandomSeed)
        rng_state = rng;
        rng_restore = onCleanup(@() rng(rng_state)); %#ok<NASGU>
        rng(options.RandomSeed);
    end

    % ---------------------------------------------------------------------------------------------------------------
    % 2. Observed PSD: Welch per piece (repo's WelchCrossSpectralDensity with x == x gives the auto-spectrum), then a
    %    segment-count-weighted average across pieces.
    % ---------------------------------------------------------------------------------------------------------------
    PSD_pieces  = zeros(n_freqs, Num_pieces);
    NumSegments = zeros(1, Num_pieces);
    for j = 1:Num_pieces
        [~, psd_j, ~, nseg_j] = WelchCrossSpectralDensity(pieces{j}, pieces{j}, fs, win_samples, overlap);
        PSD_pieces(:, j) = psd_j(:);
        NumSegments(j) = nseg_j;
    end
    PSD = PSD_pieces * NumSegments(:) / sum(NumSegments);

    % Approximate chi-square degrees of freedom of the averaged estimate. Adjacent Hann-windowed segments that
    % overlap are correlated (for 50% overlap the power correlation is 1/9), which trims the effective number of
    % independent segments; different epochs are treated as independent.
    rho = local_hann_overlap_correlation(overlap);
    K_eff = sum(NumSegments) / (1 + 2*rho);
    nu = 2 * K_eff;
    log_bias = (log(nu/2) - psi(nu/2)) / log(10);      % log10 units; added back so the fit tracks the MEAN PSD

    if any(PSD(FitMask) <= 0)
        error('SpectrumVsPowerLaw:NonPositivePSD', 'PSD has non-positive values inside the fit range (e.g. an all-zero or over-filtered signal).');
    end

    % ---------------------------------------------------------------------------------------------------------------
    % 3. Fit, residual, band excess.
    % ---------------------------------------------------------------------------------------------------------------
    [a, beta, R2, rmse_dB] = local_fit(Freqs, PSD, FitMask, options.Exponent, log_bias);
    PSD_fit = local_model(Freqs, a, beta);
    Residual_dB = 10*log10(PSD ./ PSD_fit);
    T_obs = local_band_excess_dB(PSD, PSD_fit, BandMask);

    [a1, ~] = local_fit(Freqs, PSD, FitMask, 1, log_bias);
    PSD_pink = local_model(Freqs, a1, 1);
    T_pink = local_band_excess_dB(PSD, PSD_pink, BandMask);

    res_range = Residual_dB; res_range(~RangeMask) = -Inf;
    [pk_val, pk_idx] = max(res_range);

    Result = struct();
    Result.Freqs = Freqs;
    Result.PSD = PSD;
    Result.PSD_pieces = PSD_pieces;
    Result.NumSegments = NumSegments;
    Result.fs = fs;
    Result.WindowDurationSec = win_samples / fs;
    Result.OverlapFraction = overlap;
    Result.FitMask = FitMask;
    Result.ExcludeMask = ExcludeMask;
    Result.BandMask = BandMask;
    Result.RangeMask = RangeMask;
    Result.BandHz = options.BandHz;
    Result.ExcludeHz = excl;
    Result.FitRangeHz = options.FitRangeHz;
    Result.Offset_log10 = a;
    Result.Exponent = beta;
    Result.ExponentFixed = ~isnan(options.Exponent);
    Result.PSD_fit = PSD_fit;
    Result.Residual_dB = Residual_dB;
    Result.BandExcess_dB = T_obs;
    Result.PSD_pink = PSD_pink;
    Result.BandExcess_dB_pink = T_pink;
    Result.PeakFreqHz = Freqs(pk_idx);
    Result.PeakResidual_dB = pk_val;
    Result.FitR2 = R2;
    Result.FitRMSE_dB = rmse_dB;
    Result.ExpectedFitRMSE_dB = 10/log(10) * sqrt(2/nu);   % SD of 10*log10(chi2_nu/nu) for large nu
    Result.EffectiveDoF = nu;
    Result.Null = [];
    Result.Bootstrap = [];

    if Result.FitRMSE_dB > 2 * Result.ExpectedFitRMSE_dB
        warning('SpectrumVsPowerLaw:PoorFlankFit', ...
            ['The flank fit RMS error (%.2f dB) is more than twice what estimation noise alone would give (%.2f dB): the flanks are not ' ...
             'well described by a single power law (a knee? line noise? residual filter roll-off? another peak in a flank?). ' ...
             'Inspect the residual curve before trusting the band excess.'], Result.FitRMSE_dB, Result.ExpectedFitRMSE_dB);
    end

    % ---------------------------------------------------------------------------------------------------------------
    % 4. Monte-Carlo null: Gaussian power-law noise with the fitted (a, beta), analysed with the identical pipeline.
    % ---------------------------------------------------------------------------------------------------------------
    NS = options.NumSurrogates;
    if NS > 0
        ws = warning('off', 'WelchCrossSpectralDensity:FewSegments');    % already reported once for the real data
        warn_restore = onCleanup(@() warning(ws)); %#ok<NASGU>
        model_fun = @(ff) 10^a * ff.^(-beta);      % the fitted power law, as a one-sided PSD function
        T_null = zeros(1, NS);
        beta_null = zeros(1, NS);
        Res_null = zeros(n_freqs, NS);
        max_null = zeros(1, NS);
        for s = 1:NS
            PSD_s = zeros(n_freqs, 1);
            for j = 1:Num_pieces
                x_s = SimulateColoredNoise(piece_len(j), fs, model_fun);
                [~, psd_sj] = WelchCrossSpectralDensity(x_s, x_s, fs, win_samples, overlap);
                PSD_s = PSD_s + NumSegments(j) * psd_sj(:);
            end
            PSD_s = PSD_s / sum(NumSegments);
            [a_s, beta_s] = local_fit(Freqs, PSD_s, FitMask, options.Exponent, log_bias);
            fit_s = local_model(Freqs, a_s, beta_s);
            T_null(s) = local_band_excess_dB(PSD_s, fit_s, BandMask);
            Res_null(:, s) = 10*log10(PSD_s ./ fit_s);
            max_null(s) = max(Res_null(RangeMask, s));
            beta_null(s) = beta_s;
        end
        Null = struct();
        Null.BandExcess_dB = T_null;
        Null.Exponent = beta_null;
        Null.PValue = (1 + sum(T_null >= T_obs)) / (NS + 1);
        Null.Mean_dB = mean(T_null);
        Null.SD_dB = std(T_null);
        Null.Residual_dB_lo = local_percentile(Res_null', 100*options.Alpha/2);
        Null.Residual_dB_hi = local_percentile(Res_null', 100*(1 - options.Alpha/2));
        Null.MaxThreshold_dB = local_percentile(max_null(:), 100*(1 - options.Alpha));
        sig = Residual_dB > Null.MaxThreshold_dB;
        sig(~RangeMask) = false;
        Null.FreqSignificant = sig;
        Null.NumSignificantFlankBins = sum(sig & FitMask);
        Null.NumSurrogates = NS;
        Result.Null = Null;
        if Null.NumSignificantFlankBins >= 3     % (1-2 isolated bins are what a 5%-level family-wise test throws up by chance)
            fb = Freqs(sig & FitMask);
            warning('SpectrumVsPowerLaw:ExcessInFlanks', ...
                ['%d frequency bin(s) INSIDE the fitted flanks (%.2f to %.2f Hz) exceed the family-wise threshold. Bins used to fit the ' ...
                 'line should not sit significantly above it if one power law describes the flanks, so the excess is broader than the ' ...
                 'excluded interval [%.1f %.1f] Hz. Either the bump is wider than the interval (try a larger GuardHz / ExcludeHz), or the ' ...
                 'spectrum is knee-shaped rather than peaked (see the KNEE caveat in the header). Inspect the residual curve.'], ...
                Null.NumSignificantFlankBins, min(fb), max(fb), excl(1), excl(2));
        end
    end

    % ---------------------------------------------------------------------------------------------------------------
    % 5. Bootstrap over epochs (needs >= 4 epochs): resample epochs with replacement, re-average, re-fit.
    % ---------------------------------------------------------------------------------------------------------------
    NB = options.NumBootstrap;
    if NB > 0 && Num_pieces >= 4
        T_boot = zeros(NB, 1);
        for b = 1:NB
            idx = randi(Num_pieces, 1, Num_pieces);
            w_b = NumSegments(idx);
            PSD_b = PSD_pieces(:, idx) * w_b(:) / sum(w_b);
            [a_b, beta_b] = local_fit(Freqs, PSD_b, FitMask, options.Exponent, log_bias);
            T_boot(b) = local_band_excess_dB(PSD_b, local_model(Freqs, a_b, beta_b), BandMask);
        end
        Result.Bootstrap = struct('BandExcess_dB', T_boot, ...
            'CI_dB', [local_percentile(T_boot, 100*options.Alpha/2), local_percentile(T_boot, 100*(1 - options.Alpha/2))], ...
            'NumBootstrap', NB);
    elseif NB > 0
        if options.Verbose
            fprintf(' -- (bootstrap over epochs skipped: needs >= 4 epochs, got %d)\n', Num_pieces);
        end
    end

    Result.Options = options;

    % ---------------------------------------------------------------------------------------------------------------
    % 6. Summary.
    % ---------------------------------------------------------------------------------------------------------------
    if options.Verbose
        fprintf(' -- SpectrumVsPowerLaw: %d epoch(s), %.2f s Welch window (%.3f Hz resolution), %.0f%% overlap, %d segments total (approx. %.0f dof)\n', ...
            Num_pieces, Result.WindowDurationSec, fs/win_samples, overlap*100, sum(NumSegments), nu);
        if Result.ExponentFixed
            fprintf(' -- Power law: beta FIXED at %.2f (offset fitted on %d flank bins in [%.1f %.1f] Hz excluding [%.1f %.1f] Hz)\n', ...
                beta, sum(FitMask), options.FitRangeHz(1), options.FitRangeHz(2), excl(1), excl(2));
        else
            fprintf(' -- Power law: beta = %.2f fitted on %d flank bins in [%.1f %.1f] Hz excluding [%.1f %.1f] Hz (flank RMSE %.2f dB, expected from noise alone %.2f dB)\n', ...
                beta, sum(FitMask), options.FitRangeHz(1), options.FitRangeHz(2), excl(1), excl(2), rmse_dB, Result.ExpectedFitRMSE_dB);
        end
        fprintf(' -- Excess energy in [%.1f %.1f] Hz over the power law: %+.2f dB (x%.2f)   [vs. pure 1/f (beta=1): %+.2f dB]\n', ...
            options.BandHz(1), options.BandHz(2), T_obs, 10^(T_obs/10), T_pink);
        if ~isempty(Result.Null)
            fprintf(' -- Monte-Carlo null (%d surrogates of Gaussian power-law noise): null mean %+.2f dB, SD %.2f dB, one-sided p = %.4g\n', ...
                NS, Result.Null.Mean_dB, Result.Null.SD_dB, Result.Null.PValue);
            if any(Result.Null.FreqSignificant)
                fs_bins = Freqs(Result.Null.FreqSignificant);
                fprintf(' -- Frequencies exceeding the family-wise (max-statistic, alpha=%.2f) threshold of %+.2f dB: %.2f to %.2f Hz (%d bins)\n', ...
                    options.Alpha, Result.Null.MaxThreshold_dB, min(fs_bins), max(fs_bins), numel(fs_bins));
            else
                fprintf(' -- No individual frequency exceeds the family-wise threshold (%+.2f dB).\n', Result.Null.MaxThreshold_dB);
            end
        end
        if ~isempty(Result.Bootstrap)
            fprintf(' -- Bootstrap over epochs: %.0f%% CI for the band excess = [%+.2f, %+.2f] dB\n', ...
                100*(1 - options.Alpha), Result.Bootstrap.CI_dB(1), Result.Bootstrap.CI_dB(2));
        end
        fprintf(' -- Largest residual within [%.1f %.1f] Hz: %+.2f dB at %.2f Hz\n', ...
            options.FitRangeHz(1), options.FitRangeHz(2), Result.PeakResidual_dB, Result.PeakFreqHz);
    end
end


% =================================================================================================================
% Local helpers
% =================================================================================================================
function [a, beta, R2, rmse_dB] = local_fit(freqs, psd, fit_mask, fixed_exponent, log_bias)
    % Weighted least squares of log10(PSD) on log10(f), weights proportional to 1/f (equal weight per octave).
    f = freqs(fit_mask);
    y = log10(psd(fit_mask)) + log_bias;
    x = log10(f);
    w = 1 ./ f;  w = w / sum(w);
    if isnan(fixed_exponent)
        xm = sum(w .* x);  ym = sum(w .* y);
        slope = sum(w .* (x - xm) .* (y - ym)) / sum(w .* (x - xm).^2);
        beta = -slope;
        a = ym - slope * xm;
    else
        beta = fixed_exponent;
        a = sum(w .* (y + beta * x));
    end
    yhat = a - beta * x;
    ssr = sum(w .* (y - yhat).^2);
    sst = sum(w .* (y - sum(w .* y)).^2);
    R2 = 1 - ssr / sst;
    rmse_dB = 10 * sqrt(ssr);
end

function m = local_model(freqs, a, beta)
    m = NaN(size(freqs));
    pos = freqs > 0;
    m(pos) = 10^a * freqs(pos).^(-beta);
end

function T = local_band_excess_dB(psd, psd_fit, band_mask)
    T = 10 * log10(sum(psd(band_mask)) / sum(psd_fit(band_mask)));
end

function rho = local_hann_overlap_correlation(overlap)
    % Correlation between the periodograms of two adjacent Hann-windowed segments overlapping by `overlap`.
    if overlap <= 0, rho = 0; return; end
    N = 4096;
    w = 0.5 * (1 - cos(2*pi*(0:N-1)'/N));
    s = round(N * (1 - overlap));
    rho = (sum(w(1:N-s) .* w(1+s:N)))^2 / sum(w.^2)^2;
end

function p = local_percentile(V, pct)
    % Percentile of each column of V (rows are the n samples of the statistic), with linear interpolation, so the
    % Statistics Toolbox is not required. V: [n x m] -> a [m x 1] column. A vector V is treated as one column
    % (scalar result).
    if isvector(V), V = V(:); end
    V = sort(V, 1);
    n = size(V, 1);
    pos = 1 + (n - 1) * pct / 100;
    lo = floor(pos);  hi = ceil(pos);  frac = pos - lo;
    p = V(lo, :) * (1 - frac) + V(hi, :) * frac;
    p = p(:);
end
